# -*- coding: utf-8 -*-
"""K-NN_Library_and_Non_Library

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4VtHMFyBoPteDBmsb4a0e0O-qWcCXR-

Menggunakan Library
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn import metrics
import joblib

df = pd.read_csv('StudentPerformanceFactors.csv')

df = df.dropna()

median_val = df['Exam_Score'].median()
df['Target'] = (df['Exam_Score'] >= median_val).astype(int)

le = LabelEncoder()
x = df.drop(['Exam_Score', 'Target'], axis=1)
y = df['Target']

for col in x.select_dtypes(include=['object']).columns:
    x[col] = le.fit_transform(x[col])

x_latih, x_tes, y_latih, y_tes = train_test_split(x, y, test_size=0.4, random_state=1)

scaler = StandardScaler()
x_latih_scaled = scaler.fit_transform(x_latih)
x_tes_scaled = scaler.transform(x_tes)

k_values = [4, 7, 8, 11, 12, 21, 24, 25, 27, 29]

print("HASIL PENGUJIAN K-NN DENGAN LIBRARY (SKLEARN)")
print("=" * 65)
print(f"{'K':<5} | {'Akurasi':<10} | {'Jumlah Lulus':<15} | {'Tidak Lulus':<15}")
print("-" * 65)

best_accuracy = 0
best_model = None

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(x_latih_scaled, y_latih)

    y_pred = knn.predict(x_tes_scaled)

    akurasi = metrics.accuracy_score(y_tes, y_pred)
    lulus_count = np.sum(y_pred == 1)
    tidak_lulus_count = np.sum(y_pred == 0)

    print(f"{k:<5} | {akurasi:<10.2%} | {lulus_count:<15} | {tidak_lulus_count:<15}")

    if akurasi > best_accuracy:
        best_accuracy = akurasi
        best_model = knn

joblib.dump(best_model, 'model_knn_terbaik.pkl')

print("=" * 65)
print(f"Total Data Uji: {len(y_tes)} siswa")
print(f"Model terbaik disimpan sebagai 'model_knn_terbaik.pkl'")

"""Menggunakan Non-Library"""

import pandas as pd
import numpy as np

df = pd.read_csv('StudentPerformanceFactors.csv')

df = df.dropna()

median_val = df['Exam_Score'].median()
df['Target'] = (df['Exam_Score'] >= median_val).astype(int)

obj_cols = df.select_dtypes(include=['object']).columns
for col in obj_cols:
    unique_vals = df[col].unique()
    mapping = {val: i for i, val in enumerate(unique_vals)}
    df[col] = df[col].map(mapping)

X = df.drop(['Exam_Score', 'Target'], axis=1).values
y = df['Target'].values

np.random.seed(1)
indices = np.random.permutation(len(X))
test_size = int(0.4 * len(X))
test_idx, train_idx = indices[:test_size], indices[test_size:]

X_train, X_test = X[train_idx], X[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

mean_train = np.mean(X_train, axis=0)
std_train = np.std(X_train, axis=0)
std_train[std_train == 0] = 1

X_train_scaled = (X_train - mean_train) / std_train
X_test_scaled = (X_test - mean_train) / std_train

def hitung_jarak_euclidean(titik_latih, titik_tes):
    """Menghitung jarak lurus antara dua titik data"""
    return np.sqrt(np.sum((titik_latih - titik_tes)**2, axis=1))

def prediksi_knn(X_latih, y_latih, titik_tes, k):
    """Mencari k-tetangga terdekat dan melakukan voting mayoritas"""
    jarak = hitung_jarak_euclidean(X_latih, titik_tes)

    k_indeks_terdekat = np.argsort(jarak)[:k]

    k_label_tetangga = y_latih[k_indeks_terdekat]

    prediksi = np.bincount(k_label_tetangga).argmax()
    return prediksi

k_values = [4, 7, 8, 11, 12, 21, 24, 25, 27, 29]

print("HASIL PENGUJIAN K-NN MANUAL (NON-LIBRARY)")
print("=" * 65)
print(f"{'K':<5} | {'Akurasi':<10} | {'Jumlah Lulus':<15} | {'Tidak Lulus':<15}")
print("-" * 65)

for k in k_values:
    hasil_prediksi = [prediksi_knn(X_train_scaled, y_train, x_pt, k) for x_pt in X_test_scaled]
    hasil_prediksi = np.array(hasil_prediksi)

    akurasi = np.mean(hasil_prediksi == y_test)
    lulus_count = np.sum(hasil_prediksi == 1)
    tidak_lulus_count = np.sum(hasil_prediksi == 0)

    print(f"{k:<5} | {akurasi:<10.2%} | {lulus_count:<15} | {tidak_lulus_count:<15}")

print("=" * 65)
print(f"Total Data Uji: {len(y_test)} siswa")